name: "Build documentation"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build documentation
        run: |
          ./gradlew :docs:docs && cat /home/runner/work/gradle/gradle/platforms/documentation/docs/build/working/usermanual/render-single-html/userguide_single.html
          ./gradlew --info :docs:docsTest --tests '*archives*'
